/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-08-25 08:18:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_005fpayment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/workspace/spring_mvc/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/workspace/spring_mvc/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_01/WEB-INF/lib/spring-webmvc-5.3.9.jar!/META-INF/spring-form.tld", Long.valueOf(1626212264000L));
    _jspx_dependants.put("jar:file:/C:/workspace/spring_mvc/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_01/WEB-INF/lib/spring-webmvc-5.3.9.jar!/META-INF/spring.tld", Long.valueOf(1626212264000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1627439210123L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.9.jar", Long.valueOf(1627439430870L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- BOOTSTRAP and JQuery CDN -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"orderform_wrap\" class=\"dotum\">\r\n");
      out.write("\r\n");
      out.write("		<style type=\"text/css\">\r\n");
      out.write(".chk_img {\r\n");
      out.write("	background: url('https://ftp.one-pc.co.kr/img/check_radio_icon.png')\r\n");
      out.write("		no-repeat;\r\n");
      out.write("	background-position: 0px 0px;\r\n");
      out.write("	width: 25px;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("	float: left\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".chk_img_checked {\r\n");
      out.write("	background-position: 0px -30px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cart_construct3 img {\r\n");
      out.write("	vertical-align: middle\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cart_construct3 a {\r\n");
      out.write("	color: inherit;\r\n");
      out.write("	text-decoration: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".combi_sub {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	color: #4f4f4f\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".combi_sub td {\r\n");
      out.write("	padding: 12px 20px;\r\n");
      out.write("	border-bottom: 1px solid #e9e9e9\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".combi_sub tr:last-of-type td {\r\n");
      out.write("	border: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cart_cell {\r\n");
      out.write("	width: 1160px\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("		<!-- 상단 메뉴 -->\r\n");
      out.write("		");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		<!-- 장바구니 form -->\r\n");
      out.write("		<form name=\"frmcartlist\" method=\"post\" style=\"padding: 0px;\">\r\n");
      out.write("			\r\n");
      out.write("			<!-- 리스트 내용(상품명, 상품금액, 수량 등 표시) -->\r\n");
      out.write("			<div id=\"cart_construct2\" class=\"dotum\">\r\n");
      out.write("				<table width=\"1160\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"\r\n");
      out.write("					style=\"border-top: 1px solid #5d5d5d; border-bottom: 1px solid #c8c8c8; color: #151515\"\r\n");
      out.write("					class=\"dotum bold\">\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr height=\"50\" align=\"center\">\r\n");
      out.write("							<td width=\"63\">\r\n");
      out.write("								<!-- 상세보기 -->\r\n");
      out.write("							</td>\r\n");
      out.write("							<td width=\"690\">상품명</td>\r\n");
      out.write("							<td width=\"127\">상품금액</td>\r\n");
      out.write("							<td width=\"55\">수량</td>\r\n");
      out.write("							<td width=\"123\">주문금액</td>\r\n");
      out.write("							<td width=\"102\">포인트</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"cart_construct3\" class=\"dotum\">\r\n");
      out.write("				<input type=\"hidden\" id=\"add\" name=\"add[]\" value=\"5565681473\">\r\n");
      out.write("				<input type=\"hidden\" id=\"it_amount\" name=\"it_amount[]\"\r\n");
      out.write("					value=\"329600\"> <input type=\"hidden\" name=\"ct_qty[]\"\r\n");
      out.write("					value=\"1\"> <input type=\"hidden\" id=\"ct_combi_type\"\r\n");
      out.write("					name=\"ct_combi_type[]\" value=\"0\"> <input type=\"hidden\"\r\n");
      out.write("					id=\"ct_id\" name=\"ct_id[]\" value=\"172075\"> <input\r\n");
      out.write("					type=\"hidden\" id=\"ca_id\" name=\"ca_id[]\" value=\"2010\">\r\n");
      out.write("\r\n");
      out.write("				<!-- 주문서 작성 리스트 시작 -->\r\n");
      out.write("				<div id=\"cart_cell\" align=\"center\">\r\n");
      out.write("					<table width=\"1160\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"\r\n");
      out.write("						class=\"bold\" style=\"border-bottom: 1px solid #c8c8c8\">\r\n");
      out.write("						<tbody>\r\n");
      out.write("							<tr height=\"90\">\r\n");
      out.write("								<td width=\"63\" align=\"right\"><a\r\n");
      out.write("									href=\"https://www.one-pc.co.kr/shop/item.php?it_id=5565681473\"\r\n");
      out.write("									target=\"_blink\" class=\"font12\" style=\"color: black\"> <img\r\n");
      out.write("										src=\"https://ftp.one-pc.co.kr/img/orderform_detail_btn_img.png\"\r\n");
      out.write("										alt=\"상품 상세보기\">\r\n");
      out.write("								</a></td>\r\n");
      out.write("								<td width=\"690\" align=\"center\">\r\n");
      out.write("									<!--img-->\r\n");
      out.write("									<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n");
      out.write("										<tbody>\r\n");
      out.write("											<tr valign=\"center\">\r\n");
      out.write("												<td width=\"110\" align=\"center\"><img\r\n");
      out.write("													src=\"https://item.sellpro.co.kr/data/item/473/5565681473_130.jpg\"\r\n");
      out.write("													style=\"border: 1px solid #c8c8c8\"\r\n");
      out.write("													onerror=\"this.src='https://ftp.one-pc.co.kr/img/no_image_131.gif';\"\r\n");
      out.write("													width=\"70\" height=\"70/\"></td>\r\n");
      out.write("												<td width=\"531\"><a\r\n");
      out.write("													href=\"https://www.one-pc.co.kr/shop/item.php?it_id=5565681473\"\r\n");
      out.write("													target=\"_blink\" class=\"font12\" style=\"color: black\">\r\n");
      out.write("														AMD 라이젠5-4세대 5600X (버미어) (멀티팩) </a></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</tbody>\r\n");
      out.write("									</table>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td width=\"127\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("									<div class=\"font12\"\r\n");
      out.write("										style=\"display: table; width: 100%; color: #4f4f4f\">\r\n");
      out.write("										<img src=\"https://ftp.one-pc.co.kr/img/card_icon.jpg\"\r\n");
      out.write("											style=\"float: left; margin-top: -2px\"><span\r\n");
      out.write("											id=\"ct_amount_0\" style=\"float: right\">329,600원</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td width=\"55\" align=\"center\">\r\n");
      out.write("									<div class=\"center font12\" style=\"font-weight: 400\">1</div>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td width=\"123\" align=\"center\">\r\n");
      out.write("									<!--t price-->\r\n");
      out.write("\r\n");
      out.write("									<div id=\"sell_amount_0\" class=\"font13 bold\"\r\n");
      out.write("										style=\"color: #0b6bb0;\">329,600원</div>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td width=\"102\" align=\"center\">\r\n");
      out.write("									<div id=\"sell_point_0\" class=\"font11 bold\" style=\"\">포인트 :\r\n");
      out.write("										0원</div>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("\r\n");
      out.write("					<!--  완제 기본상품 -->\r\n");
      out.write("					<input type=\"hidden\" id=\"combi_np_opt\" name=\"combi_np_opt[]\"\r\n");
      out.write("						value=\"\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 주문서작성 상품 리스트 끝 -->\r\n");
      out.write("				<input type=\"hidden\" name=\"send_cost\" value=\"\"> <input\r\n");
      out.write("					type=\"hidden\" name=\"list_count\" id=\"list_count\" value=\"1\">\r\n");
      out.write("\r\n");
      out.write("				<!-- 합계 금액 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<img src=\"https://ftp.one-pc.co.kr/img/nOrder_tit_2.png\" alt=\"결제정보\"\r\n");
      out.write("				style=\"margin-top: 30px\">\r\n");
      out.write("			<table class=\"dotum bold\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("				style=\"width: 1160px; height: 144px; background: url(https://ftp.one-pc.co.kr/img/order_info_bg.png) no-repeat 0 0; border-collapse: collapse; color: #151515; font-size: 16px; text-align: center; margin-top: 10px\">\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr height=\"68\">\r\n");
      out.write("						<td width=\"267\">상품금액</td>\r\n");
      out.write("						<td width=\"267\">추가금액(배송비)</td>\r\n");
      out.write("						<td width=\"267\">총 할인금액</td>\r\n");
      out.write("						<td>총 결제금액 <span id=\"LAY_TotalPoint\" style=\"display: none\">0원</span>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr style=\"font-size: 20px; font-family: 'nt-M'; font-weight: 400\">\r\n");
      out.write("						<td><span id=\"cart_rs_item_Price\">329,600</span>원</td>\r\n");
      out.write("						<td><span id=\"parcel_price\">0원</span></td>\r\n");
      out.write("						<td>- <span id=\"discount_price\">0</span>원\r\n");
      out.write("						</td>\r\n");
      out.write("						<td style=\"font-weight: 700\"><span id=\"LAY_TotalPrice\">329,600</span>원</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("			<input type=\"hidden\" name=\"w\" value=\"\"> <input type=\"hidden\"\r\n");
      out.write("				name=\"sw_direct\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		<form name=\"forderform\" method=\"post\" action=\"./orderupdate.php\"\r\n");
      out.write("			onsubmit=\"return forderform_check(this);\" autocomplete=\"off\"\r\n");
      out.write("			enctype=\"MULTIPART/FORM-DATA\">\r\n");
      out.write("			<input type=\"hidden\" name=\"ct_order_id[]\" class=\"ct_order_id[0]\"\r\n");
      out.write("				value=\"172075\"> <input type=\"hidden\" name=\"od_amount\"\r\n");
      out.write("				value=\"329600\"> <input type=\"hidden\" name=\"od_amount_normal\"\r\n");
      out.write("				value=\"\"> <input type=\"hidden\" name=\"od_settle_amount\"\r\n");
      out.write("				value=\"329600\"> <input type=\"hidden\" name=\"od_send_cost\"\r\n");
      out.write("				id=\"od_send_cost\" value=\"0\"> <input type=\"hidden\"\r\n");
      out.write("				name=\"od_sale_sendprice\" value=\"0\"> <input type=\"hidden\"\r\n");
      out.write("				name=\"oneday_cart_use\" value=\"\"> <input type=\"hidden\"\r\n");
      out.write("				name=\"od_bank_account\" value=\"\"> <input type=\"hidden\"\r\n");
      out.write("				name=\"comp_name_input\" value=\"\"> <input type=\"hidden\"\r\n");
      out.write("				name=\"kd_office\" value=\"\">\r\n");
      out.write("			<!-- // 2015-07-29 지점명  -->\r\n");
      out.write("\r\n");
      out.write("			<img src=\"https://ftp.one-pc.co.kr/img/nOrder_tit_1.png\"\r\n");
      out.write("				style=\"padding-bottom: 10px; margin-top: 40px\">\r\n");
      out.write("			<div\r\n");
      out.write("				style=\"display: table; width: 1160px; color: #151515; height: 540px\">\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"width: 565px; float: left; border: 1px solid #c8c8c8; height: 100%\">\r\n");
      out.write("					<div class=\"orderform_form_title\"\r\n");
      out.write("						style=\"font-size: 15px; padding: 13px 18px\">주문하시는분</div>\r\n");
      out.write("					<div style=\"padding: 25px 0 25px 40px\">\r\n");
      out.write("						<table cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("							style=\"width: 100%; border-collapse: collapse; table-layout: fixed\">\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr height=\"35\">\r\n");
      out.write("									<td class=\"orderform_form_col1\">이름</td>\r\n");
      out.write("									<td><input class=\"orderform_form_input_text\" id=\"od_name\"\r\n");
      out.write("										name=\"od_name\" type=\"text\" value=\"\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("								<tr height=\"35\">\r\n");
      out.write("									<td class=\"orderform_form_col1\">전화번호</td>\r\n");
      out.write("									<td><input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_tel1\" id=\"od_tel1\"\r\n");
      out.write("										style=\"width: 55px; text-align: center; padding: 0\" size=\"3\"\r\n");
      out.write("										maxlength=\"3\"\r\n");
      out.write("										onkeypress=\"if((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\"\r\n");
      out.write("										value=\"\"> <span style=\"padding-top: 3px;\">&nbsp;-&nbsp;</span>\r\n");
      out.write("										<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_tel2\" id=\"od_tel2\"\r\n");
      out.write("										style=\"width: 55px; text-align: center; padding: 0\" size=\"4\"\r\n");
      out.write("										maxlength=\"4\"\r\n");
      out.write("										onkeypress=\"if((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\"\r\n");
      out.write("										value=\"\"> <span style=\"padding-top: 3px;\">&nbsp;-&nbsp;</span>\r\n");
      out.write("										<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_tel3\" id=\"od_tel3\"\r\n");
      out.write("										style=\"width: 55px; text-align: center; padding: 0\" size=\"4\"\r\n");
      out.write("										maxlength=\"4\"\r\n");
      out.write("										onkeypress=\"if((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\"\r\n");
      out.write("										value=\"\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"35\">\r\n");
      out.write("									<td class=\"orderform_form_col1\">휴대폰</td>\r\n");
      out.write("									<td><input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_hp1\" id=\"od_hp1\"\r\n");
      out.write("										style=\"width: 55px; text-align: center; padding: 0\" size=\"3\"\r\n");
      out.write("										maxlength=\"3\"\r\n");
      out.write("										onkeypress=\"if((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\"\r\n");
      out.write("										value=\"\"> <span style=\"padding-top: 3px;\">&nbsp;-&nbsp;</span>\r\n");
      out.write("										<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_hp2\" id=\"od_hp2\"\r\n");
      out.write("										style=\"width: 55px; text-align: center; padding: 0\" size=\"4\"\r\n");
      out.write("										maxlength=\"4\"\r\n");
      out.write("										onkeypress=\"if((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\"\r\n");
      out.write("										value=\"\"> <span style=\"padding-top: 3px;\">&nbsp;-&nbsp;</span>\r\n");
      out.write("										<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_hp3\" id=\"od_hp3\"\r\n");
      out.write("										style=\"width: 55px; text-align: center; padding: 0\" size=\"4\"\r\n");
      out.write("										maxlength=\"4\"\r\n");
      out.write("										onkeypress=\"if((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\"\r\n");
      out.write("										value=\"\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"35\">\r\n");
      out.write("									<td class=\"orderform_form_col1\">이메일</td>\r\n");
      out.write("									<td><input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_email\" style=\"width: 250px\" value=\"undefined\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"90\">\r\n");
      out.write("									<td class=\"orderform_form_col1\">주소</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<p style=\"display: table\">\r\n");
      out.write("											<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("												name=\"od_zip1\" id=\"od_zip1\" style=\"width: 60px; float: left\"\r\n");
      out.write("												value=\"54911\" readonly=\"\"> <a\r\n");
      out.write("												href=\"javascript:openDaumPostcode('1');\" onfocus=\"blur();\"\r\n");
      out.write("												style=\"float: left\"><img\r\n");
      out.write("												src=\"https://ftp.one-pc.co.kr/img/orderform_addr_find_btn.png\"\r\n");
      out.write("												style=\"margin-left: 10px;\"></a>\r\n");
      out.write("										</p>\r\n");
      out.write("										<p style=\"margin-top: 8px\">\r\n");
      out.write("											<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("												name=\"od_addr1\" id=\"od_addr1\" style=\"width: 320px\"\r\n");
      out.write("												value=\"\" readonly=\"\">\r\n");
      out.write("										</p>\r\n");
      out.write("										<p style=\"margin-top: 8px\">\r\n");
      out.write("											<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("												name=\"od_addr2\" id=\"od_addr2\" style=\"width: 320px\"\r\n");
      out.write("												value=\"\" placeholder=\"\">\r\n");
      out.write("										</p>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"35\">\r\n");
      out.write("									<td class=\"orderform_form_col1\">주문시 요청사항</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"85\">\r\n");
      out.write("									<td><textarea name=\"od_memo\"\r\n");
      out.write("											style=\"width: 480px; height: 80px; border: 1px solid #c8c8c8; resize: none; overflow-y: scroll; box-sizing: border-box; padding: 5px\"\r\n");
      out.write("											placeholder=\"주문시 요청사항을 적어주세요.\"></textarea></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"35\" valign=\"bottom\">\r\n");
      out.write("									<td colspan=\"2\"><a href=\"javascript:;\"\r\n");
      out.write("										onclick=\"img_checkbox_mini('od_addr_save')\"\r\n");
      out.write("										style=\"display: table\">\r\n");
      out.write("											<div id=\"od_addr_save_img\"\r\n");
      out.write("												class=\"chk_img_mini chk_img_mini_checked\"></div> <span\r\n");
      out.write("											style=\"float: left; line-height: 18px; margin-left: 5px; color: #807f7f\">주문정보\r\n");
      out.write("												저장</span> <input type=\"checkbox\" name=\"od_addr_save\"\r\n");
      out.write("											id=\"od_addr_save\" value=\"1\" style=\"display: none\" checked=\"\">\r\n");
      out.write("									</a></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"width: 565px; float: right; border: 1px solid #c8c8c8; height: 100%\">\r\n");
      out.write("					<div class=\"orderform_form_title\"\r\n");
      out.write("						style=\"font-size: 15px; padding: 13px 18px\">받으시는분</div>\r\n");
      out.write("					<div style=\"padding: 25px 0 25px 40px\">\r\n");
      out.write("						<table cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("							style=\"width: 100%; border-collapse: collapse; table-layout: fixed\">\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr height=\"35\">\r\n");
      out.write("									<td class=\"orderform_form_col1\">배송지 정보</td>\r\n");
      out.write("									<td><label for=\"\" onclick=\"ct_ckb('1')\"> <a\r\n");
      out.write("											href=\"javascript:;\" onclick=\"\"\r\n");
      out.write("											style=\"display: table; float: left\">\r\n");
      out.write("												<div class=\"radio_img ct_ckb_img ct_ckb_img1\"></div> <span\r\n");
      out.write("												style=\"float: left; line-height: 18px; margin-left: 5px\">배송지\r\n");
      out.write("													주문회원 정보와 동일</span> <input type=\"radio\" name=\"ct_ckb\" id=\"ct_ckb1\"\r\n");
      out.write("												value=\"same\" style=\"display: none\">\r\n");
      out.write("										</a>\r\n");
      out.write("									</label> <label for=\"\" onclick=\"ct_ckb('2')\"> <a\r\n");
      out.write("											href=\"javascript:;\" onclick=\"\"\r\n");
      out.write("											style=\"display: table; float: left; margin-left: 20px\">\r\n");
      out.write("												<div\r\n");
      out.write("													class=\"radio_img ct_ckb_img ct_ckb_img2 radio_img_checked\"></div>\r\n");
      out.write("												<span\r\n");
      out.write("												style=\"float: left; line-height: 18px; margin-left: 5px\">배송지\r\n");
      out.write("													새로 작성하기</span> <input type=\"radio\" name=\"ct_ckb\" id=\"ct_ckb2\"\r\n");
      out.write("												value=\"new\" style=\"display: none\" checked=\"\">\r\n");
      out.write("										</a>\r\n");
      out.write("									</label></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"35\">\r\n");
      out.write("									<td class=\"orderform_form_col1\">이름</td>\r\n");
      out.write("									<td><input class=\"orderform_form_input_text\"\r\n");
      out.write("										id=\"od_b_name\" name=\"od_b_name\" type=\"text\" maxlength=\"15\"\r\n");
      out.write("										value=\"\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"35\">\r\n");
      out.write("									<td class=\"orderform_form_col1\">전화번호</td>\r\n");
      out.write("									<td><input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_b_tel1\" id=\"od_b_tel1\"\r\n");
      out.write("										style=\"width: 55px; text-align: center; padding: 0\" size=\"3\"\r\n");
      out.write("										maxlength=\"3\"\r\n");
      out.write("										onkeypress=\"if((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\"\r\n");
      out.write("										value=\"\"> <span style=\"padding-top: 3px;\">&nbsp;-&nbsp;</span>\r\n");
      out.write("										<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_b_tel2\" id=\"od_b_tel2\"\r\n");
      out.write("										style=\"width: 55px; text-align: center; padding: 0\" size=\"4\"\r\n");
      out.write("										maxlength=\"4\"\r\n");
      out.write("										onkeypress=\"if((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\"\r\n");
      out.write("										value=\"\"> <span style=\"padding-top: 3px;\">&nbsp;-&nbsp;</span>\r\n");
      out.write("										<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_b_tel3\" id=\"od_b_tel3\"\r\n");
      out.write("										style=\"width: 55px; text-align: center; padding: 0\" size=\"4\"\r\n");
      out.write("										maxlength=\"4\"\r\n");
      out.write("										onkeypress=\"if((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\"\r\n");
      out.write("										value=\"\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"35\">\r\n");
      out.write("									<td class=\"orderform_form_col1\">휴대폰</td>\r\n");
      out.write("									<td><input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_b_hp1\" id=\"od_b_hp1\"\r\n");
      out.write("										style=\"width: 55px; text-align: center; padding: 0\" size=\"3\"\r\n");
      out.write("										maxlength=\"3\"\r\n");
      out.write("										onkeypress=\"if((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\"\r\n");
      out.write("										value=\"\"> <span style=\"padding-top: 3px;\">&nbsp;-&nbsp;</span>\r\n");
      out.write("										<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_b_hp2\" id=\"od_b_hp2\"\r\n");
      out.write("										style=\"width: 55px; text-align: center; padding: 0\" size=\"4\"\r\n");
      out.write("										maxlength=\"4\"\r\n");
      out.write("										onkeypress=\"if((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\"\r\n");
      out.write("										value=\"\"> <span style=\"padding-top: 3px;\">&nbsp;-&nbsp;</span>\r\n");
      out.write("										<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("										name=\"od_b_hp3\" id=\"od_b_hp3\"\r\n");
      out.write("										style=\"width: 55px; text-align: center; padding: 0\" size=\"4\"\r\n");
      out.write("										maxlength=\"4\"\r\n");
      out.write("										onkeypress=\"if((event.keyCode<48) || (event.keyCode>57)) event.returnValue=false;\"\r\n");
      out.write("										value=\"\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"90\">\r\n");
      out.write("									<td class=\"orderform_form_col1\">주소</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<p style=\"display: table\">\r\n");
      out.write("											<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("												name=\"od_b_zip1\" id=\"od_b_zip1\"\r\n");
      out.write("												style=\"width: 60px; float: left\" value=\"\" readonly=\"\">\r\n");
      out.write("											<a href=\"javascript:openDaumPostcode('2');\" onfocus=\"blur();\"\r\n");
      out.write("												style=\"float: left\"><img\r\n");
      out.write("												src=\"https://ftp.one-pc.co.kr/img/orderform_addr_find_btn.png\"\r\n");
      out.write("												style=\"margin-left: 10px;\"></a>\r\n");
      out.write("										</p>\r\n");
      out.write("										<p style=\"margin-top: 8px\">\r\n");
      out.write("											<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("												name=\"od_b_addr1\" id=\"od_b_addr1\" style=\"width: 320px\"\r\n");
      out.write("												value=\"\" readonly=\"\">\r\n");
      out.write("										</p>\r\n");
      out.write("										<p style=\"margin-top: 8px\">\r\n");
      out.write("											<input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("												name=\"od_b_addr2\" id=\"od_b_addr2\" style=\"width: 320px\"\r\n");
      out.write("												value=\"\" placeholder=\"상세주소\">\r\n");
      out.write("										</p>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"35\">\r\n");
      out.write("									<td class=\"orderform_form_col1\">배송시 요청사항</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"85\">\r\n");
      out.write("									<td><textarea name=\"od_send_memo\"\r\n");
      out.write("											style=\"width: 480px; height: 80px; border: 1px solid #c8c8c8; resize: none; overflow-y: scroll; box-sizing: border-box; padding: 5px\"\r\n");
      out.write("											placeholder=\"배송시 요청사항을 적어주세요.\"></textarea></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"20\">\r\n");
      out.write("									<td colspan=\"2\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr height=\"35\">\r\n");
      out.write("									<td class=\"orderform_form_col1\" valign=\"top\"\r\n");
      out.write("										style=\"padding-top: 5px\">배송방법</td>\r\n");
      out.write("									<td><select id=\"od_send_case\" name=\"od_send_case\"\r\n");
      out.write("										style=\"width: 120px; height: 20px; box-sizing: border-box; border: 1px solid #c8c8c8; float: left\"\r\n");
      out.write("										onchange=\"select_send_check();\">\r\n");
      out.write("											<option value=\"default\">배송방법</option>\r\n");
      out.write("											<option value=\"택배선불\">선불택배</option>\r\n");
      out.write("											<option value=\"퀵서비스\">퀵서비스</option>\r\n");
      out.write("											<option value=\"방문수령\">방문수령</option>\r\n");
      out.write("									</select>\r\n");
      out.write("										<div id=\"how_send\"\r\n");
      out.write("											style=\"width: 270px; height: 20px; line-height: 20px; display: table; vertical-align: middle; float: left; margin-left: 15px\">\r\n");
      out.write("											-배송방법을 선택해 주시기 바랍니다.-</div>\r\n");
      out.write("										<div class=\"send_more\"\r\n");
      out.write("											style=\"clear: both; padding-top: 10px; color: #f23434; font-size: 11px\">※\r\n");
      out.write("											제주/도서 산간지역의 경우 추후 수령 시 추가 배송비가 과금될 수 있습니다.</div>\r\n");
      out.write("										<div\r\n");
      out.write("											style=\"clear: both; padding-top: 10px; color: #f23434; font-size: 11px\">\r\n");
      out.write("											<span id=\"how_send_sub_txt\"></span>\r\n");
      out.write("										</div></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div\r\n");
      out.write("				style=\"display: table; width: 1160px; color: #151515; margin-top: 40px; padding-bottom: 90px\">\r\n");
      out.write("				<div style=\"width: 565px; float: left; height: 100%\">\r\n");
      out.write("					<img src=\"https://ftp.one-pc.co.kr/img/nOrder_tit_2.png\"\r\n");
      out.write("						style=\"padding-bottom: 10px\" alt=\"결제정보\">\r\n");
      out.write("					<div style=\"border: 1px solid #c8c8c8\">\r\n");
      out.write("						<div class=\"orderform_form_title\" style=\"padding: 8px 25px\">할인정보</div>\r\n");
      out.write("						<div style=\"padding: 25px 0 25px 80px\">\r\n");
      out.write("							포인트 할인 <input class=\"orderform_form_input_text\" type=\"text\"\r\n");
      out.write("								id=\"use_point\" name=\"use_point\"\r\n");
      out.write("								style=\"height: 25px; margin-left: 20px; padding-right: 5px; text-align: right\"\r\n");
      out.write("								value=\"0\" readonly=\"\"> 원 할인 (잔액 0원)\r\n");
      out.write("							<p style=\"color: #8a8a8a; font-size: 11px; margin-top: 10px;\">\r\n");
      out.write("								※ 주문금액 [ <span class=\"bold\">1,000,000원</span> ] 이상일 경우에 사용\r\n");
      out.write("								가능합니다.\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"orderform_form_title\"\r\n");
      out.write("							style=\"padding: 8px 25px; border-top: 1px solid #c8c8c8\">결제방법\r\n");
      out.write("							선택</div>\r\n");
      out.write("						<div style=\"padding-top: 25px; padding-left: 40px\">\r\n");
      out.write("							<div style=\"display: table; padding-right: 40px; margin: 0 auto\">\r\n");
      out.write("								<a href=\"javascript:;\"\r\n");
      out.write("									onclick=\"document.getElementById('od_settle_case1').click();\"\r\n");
      out.write("									style=\"display: table; float: left\">\r\n");
      out.write("									<div class=\"radio_img od_settle_case_img od_settle_case_img1\"></div>\r\n");
      out.write("									<span style=\"float: left; line-height: 18px; margin-left: 5px\">무통장입금</span>\r\n");
      out.write("									<input type=\"radio\" name=\"od_settle_case\" id=\"od_settle_case1\"\r\n");
      out.write("									value=\"cash\" style=\"display: none\">\r\n");
      out.write("								</a> <a href=\"javascript:;\"\r\n");
      out.write("									onclick=\"document.getElementById('od_settle_case2').click();\"\r\n");
      out.write("									style=\"display: table; float: left; margin-left: 60px\">\r\n");
      out.write("									<div class=\"radio_img od_settle_case_img od_settle_case_img2\"></div>\r\n");
      out.write("									<span style=\"float: left; line-height: 18px; margin-left: 5px\">가상계좌(에스크로)</span>\r\n");
      out.write("									<input type=\"radio\" name=\"od_settle_case\" id=\"od_settle_case2\"\r\n");
      out.write("									value=\"vcash\" style=\"display: none\">\r\n");
      out.write("								</a> <a href=\"javascript:;\"\r\n");
      out.write("									onclick=\"document.getElementById('od_settle_case3').click();\"\r\n");
      out.write("									style=\"display: table; float: left; margin-left: 60px\">\r\n");
      out.write("									<div class=\"radio_img od_settle_case_img od_settle_case_img3\"></div>\r\n");
      out.write("									<span style=\"float: left; line-height: 18px; margin-left: 5px\">신용카드</span>\r\n");
      out.write("									<input type=\"radio\" name=\"od_settle_case\" id=\"od_settle_case3\"\r\n");
      out.write("									value=\"card\" style=\"display: none\">\r\n");
      out.write("								</a> <input type=\"radio\" name=\"od_settle_case\" value=\"nil\"\r\n");
      out.write("									style=\"display: none;\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div style=\"height: 25px\">\r\n");
      out.write("							<!-- 공백 -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div style=\"width: 565px; float: right; height: 100%\">\r\n");
      out.write("					<img src=\"https://ftp.one-pc.co.kr/img/nOrder_tit_4.png\"\r\n");
      out.write("						style=\"padding-bottom: 10px\" alt=\"최종결제 금액\">\r\n");
      out.write("					<div style=\"border: 1px solid #c8c8c8\">\r\n");
      out.write("						<div style=\"padding: 25px 30px 0 30px\">\r\n");
      out.write("							<ul style=\"width: 100%\">\r\n");
      out.write("								<li style=\"padding: 0 25px 20px 25px\"><img\r\n");
      out.write("									src=\"https://ftp.one-pc.co.kr/img/list_dot_img.png\"\r\n");
      out.write("									alt=\"리스트 점이미지\">주문금액\r\n");
      out.write("									<div style=\"float: right\">\r\n");
      out.write("										<span id=\"point_totalPrice\">329,600</span>원\r\n");
      out.write("									</div></li>\r\n");
      out.write("								<li style=\"padding: 0 25px 20px 25px\"><img\r\n");
      out.write("									src=\"https://ftp.one-pc.co.kr/img/list_dot_img.png\"\r\n");
      out.write("									alt=\"리스트 점이미지\">맞춤가 할인\r\n");
      out.write("									<div style=\"float: right\">\r\n");
      out.write("										- <span id=\"cash_discount\">0</span>원\r\n");
      out.write("									</div></li>\r\n");
      out.write("								<li style=\"padding: 0 25px 20px 25px\"><img\r\n");
      out.write("									src=\"https://ftp.one-pc.co.kr/img/list_dot_img.png\"\r\n");
      out.write("									alt=\"리스트 점이미지\">배송비\r\n");
      out.write("									<div style=\"float: right\">\r\n");
      out.write("										<span id=\"point_sendPrice\">0</span>원\r\n");
      out.write("									</div></li>\r\n");
      out.write("								<li style=\"padding: 0 25px 20px 25px\"><img\r\n");
      out.write("									src=\"https://ftp.one-pc.co.kr/img/list_dot_img.png\"\r\n");
      out.write("									alt=\"리스트 점이미지\">배송비할인\r\n");
      out.write("									<div style=\"float: right\">\r\n");
      out.write("										- <span id=\"point_sendDcPrice\">0</span>원\r\n");
      out.write("									</div></li>\r\n");
      out.write("								<li style=\"padding: 0 25px 15px 25px\"><img\r\n");
      out.write("									src=\"https://ftp.one-pc.co.kr/img/list_dot_img.png\"\r\n");
      out.write("									alt=\"리스트 점이미지\">포인트할인\r\n");
      out.write("									<div style=\"float: right\">\r\n");
      out.write("										- <span id=\"point_discountPrice\">0</span>원\r\n");
      out.write("									</div></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<img src=\"https://ftp.one-pc.co.kr/img/orderform_dashed.png\"\r\n");
      out.write("								style=\"display: block; margin: 0 auto\" alt=\"점선\">\r\n");
      out.write("							<div\r\n");
      out.write("								style=\"padding: 15px 25px; font-weight: 400; font-family: 'nt-M'; font-size: 20px\">\r\n");
      out.write("								총 결제 금액\r\n");
      out.write("								<div style=\"float: right; font-weight: 700;\">\r\n");
      out.write("									<span id=\"point_last_Price\">329,600</span>원\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div class=\"orderform_form_title\"\r\n");
      out.write("								style=\"padding: 8px 25px; border-top: 1px solid #c8c8c8\">주문동의</div>\r\n");
      out.write("							<div style=\"padding: 15px 0 15px 45px; color: #807f7f\">\r\n");
      out.write("								<p style=\"padding-bottom: 10px\">주문한 상품의 상품명, 상품가격, 배송정보를\r\n");
      out.write("									확인하였으며, 구매에 동의하시겠습니까?</p>\r\n");
      out.write("								<a href=\"javascript:;\" onclick=\"img_checkbox_mini('agree1')\"\r\n");
      out.write("									style=\"display: table\">\r\n");
      out.write("									<div id=\"agree1_img\" class=\"chk_img_mini\"></div> <span\r\n");
      out.write("									style=\"float: left; line-height: 18px; margin-left: 5px; color: #807f7f; font-weight: 700\">동의합니다.\r\n");
      out.write("										(전자상거래법 제8조 2항) </span> <input type=\"checkbox\" name=\"agree1\"\r\n");
      out.write("									id=\"agree1\" style=\"display: none\">\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"orderform_form_title\"\r\n");
      out.write("								style=\"padding: 8px 25px; border-top: 1px solid #c8c8c8\">개인정보\r\n");
      out.write("								취급위탁 동의</div>\r\n");
      out.write("							<div style=\"padding: 15px 0 15px 45px; color: #807f7f\">\r\n");
      out.write("								<p style=\"padding-bottom: 10px\">주문처리 및 배송을 위한 목적으로만 제공됩니다.</p>\r\n");
      out.write("								<a href=\"javascript:;\" onclick=\"img_checkbox_mini('agree2')\"\r\n");
      out.write("									style=\"display: table\">\r\n");
      out.write("									<div id=\"agree2_img\" class=\"chk_img_mini\"></div> <span\r\n");
      out.write("									style=\"float: left; line-height: 18px; margin-left: 5px; color: #807f7f; font-weight: 700\">동의합니다.</span>\r\n");
      out.write("									<input type=\"checkbox\" name=\"agree2\" id=\"agree2\"\r\n");
      out.write("									style=\"display: none\">\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div style=\"display: table; margin-top: 18px;\">\r\n");
      out.write("						<a href=\"https://www.one-pc.co.kr\" style=\"float: left\"><img\r\n");
      out.write("							src=\"https://ftp.one-pc.co.kr/img/nOrderform_btn_cancel.png\"\r\n");
      out.write("							alt=\"취소하기\"></a> <a href=\"javascript:forderform_check();\"\r\n");
      out.write("							style=\"float: left; margin-left: 19px\"><img\r\n");
      out.write("							src=\"https://ftp.one-pc.co.kr/img/nOrderform_btn_order.png\"\r\n");
      out.write("							alt=\"결재하기\"></a> <a href=\"javascript:allthe();\"\r\n");
      out.write("							style=\"float: left; margin-left: 18px\"><img\r\n");
      out.write("							src=\"https://ftp.one-pc.co.kr/img/nOrderform_btn_cardmodule.png\"\r\n");
      out.write("							alt=\"신용카드 결제 모듈설치 안내\"></a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/product/product_payment.jsp(66,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/WEB-INF/views/include/top_menu.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/product/product_payment.jsp(621,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/WEB-INF/views/include/bottom_info.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
